<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Test extends CI_Controller {

	public function __construct()
	{
		parent::__construct();
		$this->load->helper(array('url'));
		$this->load->model('Common_Model');
		$this->load->library(array('user_agent', 'functions', 'session', 'form_validation'));
    }

    public function index(){
        
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        // curl_setopt($ch, CURLOPT_URL, 'http://confluence.controlnetworks.com.au/rest/api/content/'.$id.'?expand=body.storage');
        curl_setopt($ch, CURLOPT_URL, 'http://confluence.controlnetworks.com.au/rest/api/content/?expand=body.storage&limit=100&display=KB');
        // curl_setopt($ch, CURLOPT_URL, 'http://confluence.controlnetworks.com.au/rest/api/space/KB/?limit=100');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

        curl_setopt($ch, CURLOPT_USERPWD, 'jayryan' . ':' . '@Devtugz101');

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close ($ch);
        echo $result;
        // var_dump(json_decode($result));
    }

    

}